[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
actix-files = "0.6"
dotenv = "0.15.0"
serde = "1.0.217"
actix-cors = "0.7.0"
serde_json = "1.0.134"
unofficial_appwrite = "0.2.3"